In [1]:
import pandas as pd
import requests
import json
import matplotlib
%matplotlib inline

In [2]:
with open("../data/nasa/names_dict.json") as ja:
    dictionary = json.load(ja)

In [3]:
with open("../data/nasa/exoplanet_nasa_eqt.csv") as ag:
    df = pd.read_csv(ag)

In [4]:
df = df.rename(columns = dictionary)

In [5]:
df = df.rename(columns = {'pl_eqt':'Planet Equilibrium Temperature'})

In [6]:
df["Planet Equilibrium Temperature"] = df["Planet Equilibrium Temperature"] - 273.0

In [9]:
df

,Unnamed: 0,Unnamed: 0.1,Host Star Name,Planet Letter,Planet Name,Discovery Method,Controversial Flag,Number of Planets in System,Orbital Period (days),pl_orbpererr1,...,st_massn,Stellar Radius (solar radii),st_raderr1,st_raderr2,st_radlim,st_radn,Number of Notes,Date of Last Update,Discovery Facility,Planet Equilibrium Temperature
0,0,0,CoRoT-11,b,CoRoT-11 b,Transit,0,1,2.994330,0.000011,...,5,1.37,0.03,-0.03,0.0,6,0,2014-05-14,CoRoT,1384.0
1,1,1,CoRoT-12,b,CoRoT-12 b,Transit,0,1,2.828042,0.000013,...,5,1.12,0.10,-0.09,0.0,6,0,2014-05-14,CoRoT,1169.0
2,2,2,CoRoT-13,b,CoRoT-13 b,Transit,0,1,4.035190,0.000030,...,3,1.01,0.03,-0.03,0.0,4,0,2014-05-14,CoRoT,1427.0
3,3,3,CoRoT-14,b,CoRoT-14 b,Transit,0,1,1.512140,0.000130,...,3,1.21,0.08,-0.08,0.0,4,0,2014-05-14,CoRoT,1679.0
4,4,4,CoRoT-16,b,CoRoT-16 b,Transit,0,1,5.352270,0.000200,...,2,1.19,0.14,-0.13,0.0,3,0,2014-05-14,CoRoT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4139,4139,4139,HATS-42,b,HATS-42 b,Transit,0,1,2.292102,0.000002,...,1,1.48,0.20,-0.12,0.0,2,0,2018-04-12,HATSouth,1583.0
4140,4140,4140,OGLE-2017-BLG-1522L,b,OGLE-2017-BLG-1522L b,Microlensing,0,1,NaN,NaN,...,1,NaN,NaN,NaN,0.0,0,0,2018-04-12,OGLE,NaN
4141,4141,4141,GJ 1132,c,GJ 1132 c,Radial Velocity,0,2,8.929000,0.010000,...,3,0.21,0.01,-0.01,0.0,3,1,2018-06-21,La Silla Observatory,27.0
4142,4142,4142,HAT-P-11,c,HAT-P-11 c,Radial Velocity,0,2,3407.000000,360.000000,...,7,0.68,0.01,-0.01,0.0,9,0,2019-01-31,W. M. Keck Observatory,NaN
4143,4143,4143,CoRoT-20,c,CoRoT-20 c,Radial Velocity,0,2,1675.000000,19.000000,...,5,NaN,NaN,NaN,0.0,5,0,2018-07-19,Multiple Observatories,NaN